server:
  port: 10000
  address: 0.0.0.0

lavalink:
  pluginsDir: "./plugins"
  defaultPluginRepository: "https://maven.lavalink.dev/releases"
  
  # actual plugin dependency injection
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"

  server:
    password: "${SERVER_PASSWORD}"
    sources:
      youtube: false # legacy built-in youtube source disabled!
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    gc-warnings: true

    koe:
      useEpoll: true
      gateway:
        v2: true

    #httpConfig:
      #proxyHost: "${PROXY_HOST}"     
      #proxyPort: ${PROXY_PORT}                     
      #proxyUser: "${PROXY_USER}"        
      #proxyPassword: "${PROXY_PASS}" 

plugins:
  youtube:
    enabled: true
    clients:
      - MUSIC
      - WEB
      - MWEB
      - TV
    # "let's strategize"
    clientOptions:
      MUSIC:
        playback: false      # <- CANNOT play (no sign-in prompts)
        videoLoading: false
        searching: true      # <- CAN handle text queries/metadata
      WEB:
        playback: false      # <- CANNOT play
        videoLoading: false
        searching: true      # <- CAN handle text queries/metadata
      MWEB:
        playback: false      # <- CANNOT play
        videoLoading: false
        searching: true      # <- CAN handle text queries/metadata
      TV:
        playback: true       # <- WILL handle all audio streaming (uses OAuth)
        videoLoading: true
        searching: false     # <- cannot search (failsafe)
    
    oauth:
      enabled: true
      refreshToken: "${REFRESH_TOKEN}"
      skipInitialization: true
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
      userAgent: "blasieuwu-misoyan"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    dev.lavalink.youtube: TRACE
    dev.lavalink.youtube.clients: TRACE
    dev.lavalink.youtube.http.YoutubeAccessTokenTracker: DEBUG
    com.sedmelluq.discord.lavaplayer: DEBUG

  logback:
    rollingpolicy:
      max-history: 30
      max-size: 1GB
